# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target ‘Viva-challenge’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'
  pod ’SnapKit'

  target ‘Viva-challengeTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end

end
